### ISSUE TITLE
Useful apps to add on your build

### ISSUE THREAD

**Issue by stich86** [4IceG/ZTE-MF286D#1]
Hi @4IceG 

I think it will be useful to have also:

- picocom (to access modem over serial and send AT commands)
- tcpdump or tcpdump-mini (for debugging)
- nlbwmon for bandwidth monitor

Thx :)

**Comment by 4IceG** [comment]
HI @stich86 
No problem :), I can add the first two programs to the image, although the at commands can already be sent using sms-tool / atinout. I have already added a nice program to statistics
wrtbwmon.

**Comment by 4IceG** [comment]
I know that the package counts the total transfer, but personally I am more guided by the consumption of the operator, I have 200GB/m myself.

**Comment by 4IceG** [comment]
Hi @stich86 
I have already added the packages: picocom and tcpdump.

**Comment by stich86** [comment]
can you add those packages:

- adb (use to access modem and push FOTA)
- curl

thx!

**Comment by 4IceG** [comment]
Hi @stich86 
Done ;)

**Comment by stich86** [comment]
sorry man, can you add also those packages (i'm trying to make QPST working on OpenWRT when modem is in EDL):

- kmod-usb-serial-qualcomm
- socat
- ser2net
- watchcat (+ luci)

thx!

**Comment by 4IceG** [comment]
I have added packages, but I don't know what else watchcat for, since the image already contains packages:
- luci-app-internet-detector
- luci-app-lite-watchdog
