### ISSUE TITLE
wwan0 does not reconnect automatically

### ISSUE THREAD

**Issue by dandare1980** [4IceG/ZTE-MF286D#12]
Thanks for the custom firmware, it's made getting started with Openwrt on this router modem very easy.

I'm having an issue with the cellular connection dropping every couple of hours, then it won't connect until I manually restart wwan0 (or reboot the router).

Is their a way for the modem to do this automatically?

**Comment by 4IceG** [comment]
Hi, 
Try to set a connection monitor for the interface on which the modem is working. OpenWrt is not always able to reconnect, sometimes it needs help (using additional packages or scripts).

**Comment by dandare1980** [comment]
I found within the pages of the [OpenWrt Wiki](https://openwrt.org/docs/guide-user/network/wan/wwan/ltedongle#how_to_use_lte_modem_in_qmi_mode_for_wan_connection) a way to pass commands to the modem in uci using the package `uqmi`, with options not available through Luci.

`uqmi --device=/dev/cdc-wdm0 --autoconnect`
`uqmi --device=/dev/cdc-wdm0 --set-autoconnect enabled`

Not sure if it will have the desired effect, but I should know by the morning.

**Comment by dandare1980** [comment]
Please accept my apologies, I completely ignored your directions to the "Connection Monitor" under "Services" which I've just set up.

Hopefully this will help.
