### ISSUE TITLE
how to change imei?

### ISSUE THREAD

**Issue by fabio1999ita** [4IceG/ZTE-MF286D#13]
how to change imei?

**Comment by fabio1999ita** [comment]
> IMEI isn't meant to be changed. You cannot do that. It is permanently assigned to your cell device.

i already changed it, thx anyway

**Comment by pianist** [comment]
> i already changed it, thx anyway

How did you do that? mdm9250?

**Comment by fabio1999ita** [comment]
> > i already changed it, thx anyway
> 
> How did you do that? mdm9250?

you need to flash to null the image download it, change imei with some tools and reflash into router
now i not remember, but it take a lot of time to me to do it
