### ISSUE TITLE
Cannot use official repo

### ISSUE THREAD

**Issue by stich86** [4IceG/ZTE-MF286D#2]
Hi @4IceG I've tried your image but is not possible to use official snapshot because there is signature error.

Can you fix the build?

Thx

**Comment by 4IceG** [comment]
HI @stich86
I don't know why, but I have a problem with certificates, only when I turn off certificate verification, I can download and install everything.

**Comment by stich86** [comment]
> HI @stich86
> 
> I don't know why, but I have a problem with certificates, only when I turn off certificate verification, I can download and install everything.

How to turn it off?

Thx

**Comment by 4IceG** [comment]
I will write later because now I do not remember where I set it.

**Comment by 4IceG** [comment]
Ok I get around this problem like this:
System > Software > Configure opkg....

Delete line:
option check_signature
And click Save

**Comment by stich86** [comment]
> Ok I get around this problem like this:
> 
> System > Software > Configure opkg....
> 
> 
> 
> Delete line:
> 
> option check_signature
> 
> And click Save
> 
> 

Nice!

Thanks :)

**Comment by 4IceG** [comment]
@stich86 
Any interesting packages you wanted to add? something functional is still missing? :)

**Comment by 4IceG** [comment]
Hi @stich86 
I switched from master to openwrt-22.03 and now repositories work.
