### ISSUE TITLE
Curl command missing

### ISSUE THREAD

**Issue by SuperKali** [4IceG/ZTE-MF286D#3]
Hi, can you check why curl is not found?

**Comment by SuperKali** [comment]
![image](https://user-images.githubusercontent.com/19473898/180605139-b602928c-1f46-4084-aa13-008a51a038c7.png)

**Comment by 4IceG** [comment]
Hi @SuperKali 
Install the image I have now provided, already should disappear to be problems with packages.

**Comment by SuperKali** [comment]
curl is not found, i need curl

**Comment by 4IceG** [comment]
![c1](https://user-images.githubusercontent.com/59826889/180606030-231ee263-54b8-477f-8647-9eff6bfc8b49.PNG)
![c2](https://user-images.githubusercontent.com/59826889/180606031-248a1245-3400-46f6-ad4c-2ec81f2e4146.PNG)

It doesn't, but you can install it.
