### ISSUE TITLE
System read-only

### ISSUE THREAD

**Issue by SuperKali** [4IceG/ZTE-MF286D#4]
Hi, I experienced a problem on filesystem:
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/perlbase-cwd.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/kmod-crypto-gcm.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/sms-tool.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/f2fsck.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/kmod-ath10k-ct.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-lib-nixio.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/comgt-ncm.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/libubox20220515.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-app-sms-tool.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/collectd-mod-rrdtool.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/ca-bundle.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/libuclient20201210.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/liblucihttp-lua.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/perlbase-base.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/kmod-nls-iso8859-1.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-i18n-ddns-pl.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/kmod-crypto-cmac.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/umbim.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-lib-jsonc.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/collectd-mod-memory.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/qmi-utils.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/kmod-crypto-rng.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/libgcc1.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/kmod-usb-ledtrig-usbport.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-app-ksmbd.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/libstdcpp6.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/perlbase-selectsaver.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/vpnbypass.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/sysinfo.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/librrd1.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-i18n-3ginfo-lite-pl.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/kmod-ath.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/kmod-crypto-lib-curve25519.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/ubox.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/kmod-crypto-crc32.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/kmod-crypto-lib-chacha20.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/libqrtr-glib.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/aria2.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/rpcd-mod-iwinfo.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-mod-network.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/kmod-nft-core.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-i18n-opkg-en.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/libltdl7.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-i18n-base-en.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/libatomic1.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-i18n-firewall-pl.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/picocom.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/uhttpd-mod-ubus.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/wget-ssl.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/fwtool.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-app-cpu-status-mini.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/wwan.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/jsonfilter.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/modemband.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/hostapd-common.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/collectd-mod-cpu.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/kmod-usb-net-cdc-ether.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/libattr.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-i18n-lite-watchdog-pl.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/wireless-regdb.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/perlbase-params.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/kmod-scsi-core.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/urngd.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/perlbase-errno.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/kmod-slhc.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-i18n-cpu-status-mini-pl.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/kmod-cfg80211.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/rpcd-mod-rrdns.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/ppp-mod-pppoe.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-app-openvpn.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/perlbase-posix.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/libnghttp2-14.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-i18n-mbim-pl.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/libnl-genl200.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/iptables-zz-legacy.list: Read-only file system.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-proto-ncm.list: Read-only file system.
 
 Is in read-only, can I fix without send another update because this modem is on another country where my mother live.

**Comment by SuperKali** [comment]
after 24 hours it happened, with openwrt stock not happen

**Comment by SuperKali** [comment]
The problem is caused by a manual update of base-files

**Comment by 4IceG** [comment]
There are a lot of topics on the OpenWrt forum where they advise against installing packages manually.
