### ISSUE TITLE
Release the source code

### ISSUE THREAD

**Issue by SuperKali** [4IceG/ZTE-MF286D#5]
Hi can you release your configuration which people can re-compile with your and another packages?

**Comment by 4IceG** [comment]
Hi @SuperKali , but what do you want me to share my config.buildinfo file?

**Comment by SuperKali** [comment]
Hi, @4IceG i mean like this:
![image](https://user-images.githubusercontent.com/19473898/184086122-b3eecfcf-39f8-4cc0-bd4d-c23d842b3d87.png)

**Comment by 4IceG** [comment]
Hi @SuperKali , I prepared my sources, nothing but to compile.
[https://drive.google.com/file/d/17LHIKJVv5PiKNAVzkXlVKDV8Ang3QZ7q/view?usp=sharing](url)

**Comment by SuperKali** [comment]
Thanks <3
