### ISSUE TITLE
Missing VXLAN kmods and they are impossible to install

### ISSUE THREAD

**Issue by Wyk72** [4IceG/ZTE-MF286D#6]
I am trying your build on my ZTE-MF286D, but since it's a snapshot build I can't install any kernel modules I need. One in particular I need is VXLAN that is missing, and it seems opkg spews out the usual errors:

kmod-vxlan_5.15.84-1_arm_cortex-a7_neon-vfpv4.ipk  ser2net.conf
root@MF286D:/tmp# opkg install ./kmod-vxlan_5.15.84-1_arm_cortex-a7_neon-vfpv4.ipk
Unknown package 'kmod-vxlan'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.86-1-4e4a9d1c50cb9e3f6fa990c117a587e0) for kmod-iptunnel
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.86-1-4e4a9d1c50cb9e3f6fa990c117a587e0) for kmod-udptunnel4
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.86-1-4e4a9d1c50cb9e3f6fa990c117a587e0) for kmod-udptunnel6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.84-1-4e4a9d1c50cb9e3f6fa990c117a587e0) for kmod-vxlan
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-vxlan found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-vxlan.

There is a way to find those kmods ..somewhere ? Do I need to add a repository or something ?

I have the right ipk I think, but the system keeps falling apart and does not let me use the kmods. Very frustrating.

**Comment by 4IceG** [comment]
Hi @Wyk72 , try manually download and install the missing dependencies.

[kmods >5.15.86](https://downloads.openwrt.org/snapshots/targets/ipq40xx/generic/kmods/5.15.86-1-4e4a9d1c50cb9e3f6fa990c117a587e0/)

**Comment by Wyk72** [comment]
Tried, got packages but it complains about the version the repos and all and does not let me install the packages, the kmods and all.

Even manually the system does not let me install anything, even using the correct packages from kernel 5.15.84-1. This is so stupid.

**Comment by Wyk72** [comment]
Also, eve if I get the vxlan loaded correctly, ip link statement does not work and I have no idea why: I use 

ip link

all the time, but this openwrt custom (?) version does not let me.


root@MF286D:~# ip link add sm0 type vxlan remote 10.20.30.50 id 1 dstport 4789 noudpcsum udp6zerocsumtx udp6zerocsumrx
Garbage instead of arguments "remote ...". Try "ip link help".


root@MF286D:~# ip link add name sm0 type vxlan id 1 dev TechnoGeneral remote 10.20.30.50 local 192.168.111.1  dstport 4789
Garbage instead of arguments "id ...". Try "ip link help".


NOBODY in the universe knows the correct syntax for this "ip link" statement (that works on ANY linux box I use, and I use plenty of them) which is plain dumb.

**Comment by 4IceG** [comment]
I'll check it out and try to install these packages for myself.

**Comment by 4IceG** [comment]
Unfortunately, I can't install either.

We will do differently, I will create a new "generic" repository on github and you will be able to download what is missing from it.

**Comment by 4IceG** [comment]
Ok, done.

1. Add the following entry to the /etc/opkg/customfeeds.conf file to the OpenWrt router:

`src/gz mygeneric https://github.com/4IceG/Modem-extras/raw/main/mygeneric`

3. Add repository public key with commands:

```
wget https://github.com/4IceG/Modem-extras/raw/main/mygeneric/IceG-repo.pub -O /tmp/IceG-repo.pub
opkg-key add /tmp/IceG-repo.pub
```

**Comment by Wyk72** [comment]
Thanks a million.

Still this doesnot seem to work:

root@MF286D:~# opkg install luci-proto-vxlan
Installing luci-proto-vxlan (git-21.148.48881-79947af) to root...
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/luci-proto-vxlan_git-21.148.48881-79947af_all.ipk
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.84-1-4e4a9d1c50cb9e3f6fa990c117a587e0) for kmod-iptunnel
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.86-1-4e4a9d1c50cb9e3f6fa990c117a587e0) for kmod-udptunnel4
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.86-1-4e4a9d1c50cb9e3f6fa990c117a587e0) for kmod-udptunnel6
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.84-1-4e4a9d1c50cb9e3f6fa990c117a587e0) for kmod-vxlan
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-proto-vxlan:
 *      kernel (= 5.15.86-1-4e4a9d1c50cb9e3f6fa990c117a587e0)
 * opkg_install_cmd: Cannot install package luci-proto-vxlan.

I have no idea why it keeps referring to the wrong kernel.

**Comment by 4IceG** [comment]
Did you update the repository?
`opkg update`

Before installation..

**Comment by Wyk72** [comment]
yes of course

**Comment by Wyk72** [comment]
root@MF286D:~# opkg update
Downloading https://github.com/4IceG/Modem-extras/raw/main/myrepo/Packages.gz
Updated list of available packages in /var/opkg-lists/IceG_repo
Downloading https://github.com/4IceG/Modem-extras/raw/main/myrepo/Packages.sig
Signature check passed.
Downloading https://github.com/4IceG/Modem-extras/raw/main/mygeneric/Packages.gz
Updated list of available packages in /var/opkg-lists/mygeneric
Downloading https://github.com/4IceG/Modem-extras/raw/main/mygeneric/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/targets/ipq40xx/generic/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_core
Downloading https://downloads.openwrt.org/snapshots/targets/ipq40xx/generic/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/base/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_base
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/base/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_luci
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/luci/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_packages
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/packages/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_routing
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/routing/Packages.sig
Signature check passed.
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_telephony
Downloading https://downloads.openwrt.org/snapshots/packages/arm_cortex-a7_neon-vfpv4/telephony/Packages.sig
Signature check passed.
Downloading http://downloads.openwrt.org/snapshots/targets/ipq40xx/generic/kmods/5.15.84-1-4e4a9d1c50cb9e3f6fa990c117a587e0//Packages.gz
Updated list of available packages in /var/opkg-lists/openwrt_kmods
Downloading http://downloads.openwrt.org/snapshots/targets/ipq40xx/generic/kmods/5.15.84-1-4e4a9d1c50cb9e3f6fa990c117a587e0//Packages.sig
Signature check passed.

**Comment by 4IceG** [comment]
I will check if I can install the package..

**Comment by 4IceG** [comment]
Uh.. Don't want to install..

**Comment by 4IceG** [comment]
And I added exactly what I compiled in the image.. Uh..

I will quickly compile an image with this package and add it here..

**Comment by 4IceG** [comment]
[openwrt-snapshot-r21703-4965cbd259-ipq40xx-generic-zte_mf286d-squashfs-sysupgrade.zip](https://github.com/4IceG/ZTE-MF286D/files/10366097/openwrt-snapshot-r21703-4965cbd259-ipq40xx-generic-zte_mf286d-squashfs-sysupgrade.zip)

**Comment by Wyk72** [comment]
Thanks a million you are the kindest guy. This version you compiled has the right kernel (5.15.86) so the pkg manager does not complain.

Also VXlan is present and hoperfully will work. I use it to avoid CGNAT for my LTE connection, is vital to my setup.

This OpenWRT makes this router a true jewel: 4core ARM, very good wifi, a 100% manageable LTE connection. Extremely rare, if not UNIQUE.
